name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1.1.0
    - run: yarn ci
    - run: yarn test
      env:
        CI: true
